#bin!bash
declare -a arr=("acase_answers"
"csequences"
"pictures"
"acase_correct_feelings"
"csquares"
"acases"
"evaluations"
"schools"
"ace_acases"
"fgroup_items"
"situation_sets"
"aces"
"fonotest_items"
"students"
"fonotests"
"users"
"audios"
"hnf_answers"
"wallies"
"communes"
"hnfset_hnftests"
"wfeelings"
"corsi_csequences"
"hnfsets"
"wreactions"
"corsi_evaluations"
"hnftest_figures"
"wsituation_answers"
"corsis"
"hnftests"
"wsituations"
"courses"
"item_answers"
"csequence_answers"
"items"
)
mkdir backups
filename="production.sqlite3"
for i in "${arr[@]}"
do
    sqlite3 -header -csv $filename "select * from $i">"backups/$i.csv"
   echo "$i"
   # or do whatever with individual element of the array
done

